name: CD Pipeline (Deploy to Spaces)

on:
  push:
    branches: ["main"]

jobs:
  deploy-to-spaces:
    runs-on: ubuntu-latest
    needs: [quality-check] # Wait for CI to pass first!

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # UPDATE THESE TWO LINES:
          HF_USERNAME: vardan10
          SPACE_NAME: Sokratik-API
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          git push --force space main
